[[pocl_standalone]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6b138526e383711ae5cef2f063eebb69d849f133"
libc = "glibc"
os = "linux"

    [[pocl_standalone.download]]
    sha256 = "0293c3fef1a68b4fab53da027437d6c47fac5186aada6a36ebd89f5703f8aee6"
    url = "https://github.com/JuliaBinaryWrappers/pocl_standalone_jll.jl/releases/download/pocl_standalone-v7.2.1+2/pocl_standalone.v7.2.1.i686-linux-gnu-cxx11.tar.gz"
[[pocl_standalone]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7b2ea7a294503711fd1bf82468b429e2b84ded5b"
libc = "glibc"
os = "linux"

    [[pocl_standalone.download]]
    sha256 = "9aa67df35cffb6a51c75ac2df86a4b04192277391bdbe4206e1f94b8fb3fcbd9"
    url = "https://github.com/JuliaBinaryWrappers/pocl_standalone_jll.jl/releases/download/pocl_standalone-v7.2.1+2/pocl_standalone.v7.2.1.x86_64-linux-gnu-cxx11.tar.gz"
[[pocl_standalone]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4652b23b2eb9daa7941cb8784708c3e330309627"
libc = "glibc"
os = "linux"

    [[pocl_standalone.download]]
    sha256 = "2f68912ae76cb273ec508bd472a614394f33f7ef725c04501d30caf1c761f827"
    url = "https://github.com/JuliaBinaryWrappers/pocl_standalone_jll.jl/releases/download/pocl_standalone-v7.2.1+2/pocl_standalone.v7.2.1.aarch64-linux-gnu-cxx11.tar.gz"
[[pocl_standalone]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f557dfea51352904c500cb251ec291b492b1de76"
libc = "glibc"
os = "linux"

    [[pocl_standalone.download]]
    sha256 = "aa5386be77ba5a27ae7a71c5153af9b10dd1510e874c95eb288651867f5ee5bf"
    url = "https://github.com/JuliaBinaryWrappers/pocl_standalone_jll.jl/releases/download/pocl_standalone-v7.2.1+2/pocl_standalone.v7.2.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[pocl_standalone]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1585487e15f11177ab0e15f906dbb23fb789d50f"
libc = "glibc"
os = "linux"

    [[pocl_standalone.download]]
    sha256 = "10420a4de77106dedd4d883fa7b3180145b636ade465677cec6f659a37988bc1"
    url = "https://github.com/JuliaBinaryWrappers/pocl_standalone_jll.jl/releases/download/pocl_standalone-v7.2.1+2/pocl_standalone.v7.2.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[pocl_standalone]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db9cd04a7b410dfbea4ae79c58d9ee2398250679"
libc = "glibc"
os = "linux"

    [[pocl_standalone.download]]
    sha256 = "3201eb6520fa6b0abf9e8567e470c9bb11c880fc2ad333e4c67c773134018a23"
    url = "https://github.com/JuliaBinaryWrappers/pocl_standalone_jll.jl/releases/download/pocl_standalone-v7.2.1+2/pocl_standalone.v7.2.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[pocl_standalone]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c09c8db0723dee29a654a93b7197ead3934cf02f"
libc = "glibc"
os = "linux"

    [[pocl_standalone.download]]
    sha256 = "0d6c79c71338ff9d7a4c4803b60ea188b9a9ea6a950c88211186ab2b667fb0d9"
    url = "https://github.com/JuliaBinaryWrappers/pocl_standalone_jll.jl/releases/download/pocl_standalone-v7.2.1+2/pocl_standalone.v7.2.1.riscv64-linux-gnu-cxx11.tar.gz"
[[pocl_standalone]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e07a3420dac07af8db1e9e1bba63691ee9b08755"
libc = "musl"
os = "linux"

    [[pocl_standalone.download]]
    sha256 = "13a6f3f959e0047a7ebc081eeb5d1c5ec1479592c095c02fa0abb59d2d293663"
    url = "https://github.com/JuliaBinaryWrappers/pocl_standalone_jll.jl/releases/download/pocl_standalone-v7.2.1+2/pocl_standalone.v7.2.1.x86_64-linux-musl-cxx11.tar.gz"
[[pocl_standalone]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "08f553a0e530f692f7a42c59a284d7473504ce34"
libc = "musl"
os = "linux"

    [[pocl_standalone.download]]
    sha256 = "111cd965c2a23caebe3de18b79356c41a33b25e9f8879f2170e18b3813ddec42"
    url = "https://github.com/JuliaBinaryWrappers/pocl_standalone_jll.jl/releases/download/pocl_standalone-v7.2.1+2/pocl_standalone.v7.2.1.aarch64-linux-musl-cxx11.tar.gz"
[[pocl_standalone]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "35ad2a0087bb45fc1263f5f56bb9012d34dcdd2a"
libc = "musl"
os = "linux"

    [[pocl_standalone.download]]
    sha256 = "a1771563bcbf3b4eb84b3ec27cb557b6c7106ea2337403483e389f381b0bbca4"
    url = "https://github.com/JuliaBinaryWrappers/pocl_standalone_jll.jl/releases/download/pocl_standalone-v7.2.1+2/pocl_standalone.v7.2.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[pocl_standalone]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e125c7acd9d48c5cd13b042ce6d555e66d80c44b"
libc = "musl"
os = "linux"

    [[pocl_standalone.download]]
    sha256 = "fc7e6dddfb34eead29db257010c22726c74f30b788cb7417eae569708f76f8ef"
    url = "https://github.com/JuliaBinaryWrappers/pocl_standalone_jll.jl/releases/download/pocl_standalone-v7.2.1+2/pocl_standalone.v7.2.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[pocl_standalone]]
arch = "x86_64"
git-tree-sha1 = "a3cf875af2bc4477bf50003c33209b70c7159d06"
os = "macos"

    [[pocl_standalone.download]]
    sha256 = "75384c714977f5995aaa1321011e8bd0ed4ea4aa8290a2562f3623e4e7931ef6"
    url = "https://github.com/JuliaBinaryWrappers/pocl_standalone_jll.jl/releases/download/pocl_standalone-v7.2.1+2/pocl_standalone.v7.2.1.x86_64-apple-darwin.tar.gz"
[[pocl_standalone]]
arch = "aarch64"
git-tree-sha1 = "9d5111b4d32f70ed1edb1a6dee6bd91f83f69823"
os = "macos"

    [[pocl_standalone.download]]
    sha256 = "ae3e107afde4656c9d44e317cee4325b14eaa6b30b8a6a1902a20907b2a342f6"
    url = "https://github.com/JuliaBinaryWrappers/pocl_standalone_jll.jl/releases/download/pocl_standalone-v7.2.1+2/pocl_standalone.v7.2.1.aarch64-apple-darwin.tar.gz"
[[pocl_standalone]]
arch = "x86_64"
git-tree-sha1 = "efb5a91d1e058208130035e23411ea11210204d1"
os = "freebsd"

    [[pocl_standalone.download]]
    sha256 = "52ea566adee14e76fe20f84ec53b4d70a4c79d51d704e9c2c31f1c3e2364edc2"
    url = "https://github.com/JuliaBinaryWrappers/pocl_standalone_jll.jl/releases/download/pocl_standalone-v7.2.1+2/pocl_standalone.v7.2.1.x86_64-unknown-freebsd.tar.gz"
[[pocl_standalone]]
arch = "aarch64"
git-tree-sha1 = "95e242bdd366be2d5af49bbd594c83dd4ebce5d6"
os = "freebsd"

    [[pocl_standalone.download]]
    sha256 = "49b97c166f7f63e48c695a1ef140ea7a9a8a538fd85f49b940b4f133d5afa1a0"
    url = "https://github.com/JuliaBinaryWrappers/pocl_standalone_jll.jl/releases/download/pocl_standalone-v7.2.1+2/pocl_standalone.v7.2.1.aarch64-unknown-freebsd.tar.gz"
[[pocl_standalone]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "170f7919f050a3f897a7f4b40b5c981a215b827e"
os = "windows"

    [[pocl_standalone.download]]
    sha256 = "27f893af160d3848327d2910316ec6afa84f76128d9d05cc60803ab85de92f0b"
    url = "https://github.com/JuliaBinaryWrappers/pocl_standalone_jll.jl/releases/download/pocl_standalone-v7.2.1+2/pocl_standalone.v7.2.1.x86_64-w64-mingw32-cxx11.tar.gz"
