[[pocl_standalone]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ea66df7e55a26b8e614893a9a220f041fa027d22"
libc = "glibc"
os = "linux"

    [[pocl_standalone.download]]
    sha256 = "0aa76853581be5fa1c12c8b823c2a6daf2242cee7cf63fa52bda640ebb563a23"
    url = "https://github.com/JuliaBinaryWrappers/pocl_standalone_jll.jl/releases/download/pocl_standalone-v7.1.2+2/pocl_standalone.v7.1.2.i686-linux-gnu-cxx11.tar.gz"
[[pocl_standalone]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "112b742c63cb200c691df91d8a5d957fcc4762ee"
libc = "glibc"
os = "linux"

    [[pocl_standalone.download]]
    sha256 = "1ad000ded7c1354fbf2255a760d65dba4bd6d36aafcdaecad7cb97ea4c08267c"
    url = "https://github.com/JuliaBinaryWrappers/pocl_standalone_jll.jl/releases/download/pocl_standalone-v7.1.2+2/pocl_standalone.v7.1.2.x86_64-linux-gnu-cxx11.tar.gz"
[[pocl_standalone]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cb769d0c8b3c3af5a3eb0a340795f8554cf9802e"
libc = "glibc"
os = "linux"

    [[pocl_standalone.download]]
    sha256 = "8c905154fc7f265e57dc1b3eba1de307ce714fe451dc6ca23dce051ddb2ec484"
    url = "https://github.com/JuliaBinaryWrappers/pocl_standalone_jll.jl/releases/download/pocl_standalone-v7.1.2+2/pocl_standalone.v7.1.2.aarch64-linux-gnu-cxx11.tar.gz"
[[pocl_standalone]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d4f0c3caca2edcaf43133e0bccf28bbe5dec5bcb"
libc = "glibc"
os = "linux"

    [[pocl_standalone.download]]
    sha256 = "408f1f22e3a2f61786d83749f572428738fefd75668c5bef63f17a334c7c3f0b"
    url = "https://github.com/JuliaBinaryWrappers/pocl_standalone_jll.jl/releases/download/pocl_standalone-v7.1.2+2/pocl_standalone.v7.1.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[pocl_standalone]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dccde9d8215e2f5a0f598f02d06ac967d1934b55"
libc = "glibc"
os = "linux"

    [[pocl_standalone.download]]
    sha256 = "fd70c12f65e88c8676a3b9d2e3aa96e96d27606bb57057c5be59974c7f84bb37"
    url = "https://github.com/JuliaBinaryWrappers/pocl_standalone_jll.jl/releases/download/pocl_standalone-v7.1.2+2/pocl_standalone.v7.1.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[pocl_standalone]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b732851cc5fdd3ec141906e0a047c2169a54a49f"
libc = "glibc"
os = "linux"

    [[pocl_standalone.download]]
    sha256 = "8343c87c4b6f6733bc12b75c7fcbe214e56e81a1c2254267fe82e0047541fc58"
    url = "https://github.com/JuliaBinaryWrappers/pocl_standalone_jll.jl/releases/download/pocl_standalone-v7.1.2+2/pocl_standalone.v7.1.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[pocl_standalone]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "534f939693e906f255b02b6dee070c97d1d918d4"
libc = "glibc"
os = "linux"

    [[pocl_standalone.download]]
    sha256 = "c58276f7031c88b8fd1cab8d16eb54a375d23470b6aff523bf74860212ac9033"
    url = "https://github.com/JuliaBinaryWrappers/pocl_standalone_jll.jl/releases/download/pocl_standalone-v7.1.2+2/pocl_standalone.v7.1.2.riscv64-linux-gnu-cxx11.tar.gz"
[[pocl_standalone]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "73b09f5e5a267f199dfe796b1b5eec739f09a88f"
libc = "musl"
os = "linux"

    [[pocl_standalone.download]]
    sha256 = "f17ccae306bea9353216ed250da60bb978d41adcf541024906ee07387efb394d"
    url = "https://github.com/JuliaBinaryWrappers/pocl_standalone_jll.jl/releases/download/pocl_standalone-v7.1.2+2/pocl_standalone.v7.1.2.x86_64-linux-musl-cxx11.tar.gz"
[[pocl_standalone]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1aae5e576de8c8aa41508f7a82e5b36641d5a836"
libc = "musl"
os = "linux"

    [[pocl_standalone.download]]
    sha256 = "efb6e8a514d0350fdb62e26588f3854e3ffbd1cd517de8c61c3f0d85efdd8aa7"
    url = "https://github.com/JuliaBinaryWrappers/pocl_standalone_jll.jl/releases/download/pocl_standalone-v7.1.2+2/pocl_standalone.v7.1.2.aarch64-linux-musl-cxx11.tar.gz"
[[pocl_standalone]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "85126e777176e1b3e46bf12974ae2e1f4d13dea2"
libc = "musl"
os = "linux"

    [[pocl_standalone.download]]
    sha256 = "0c88c984a04c7b6ff9e65195c4b3ff44c2da6ce22ed3902683c656b54143ad28"
    url = "https://github.com/JuliaBinaryWrappers/pocl_standalone_jll.jl/releases/download/pocl_standalone-v7.1.2+2/pocl_standalone.v7.1.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[pocl_standalone]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a558914c80a25b3dd73c7089d2e48c017ee07f5"
libc = "musl"
os = "linux"

    [[pocl_standalone.download]]
    sha256 = "b61dcb2b12b2d7cdc690794ab9d062929d0848abfc8fbd7978eeac72a7640f26"
    url = "https://github.com/JuliaBinaryWrappers/pocl_standalone_jll.jl/releases/download/pocl_standalone-v7.1.2+2/pocl_standalone.v7.1.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[pocl_standalone]]
arch = "x86_64"
git-tree-sha1 = "3444ac03777e16d36ff972495c0ed9f516f1e742"
os = "macos"

    [[pocl_standalone.download]]
    sha256 = "01eb0ca53e0b7cad67d9cfef1e54520d7241ef2c1d48ea7178e270e321345180"
    url = "https://github.com/JuliaBinaryWrappers/pocl_standalone_jll.jl/releases/download/pocl_standalone-v7.1.2+2/pocl_standalone.v7.1.2.x86_64-apple-darwin.tar.gz"
[[pocl_standalone]]
arch = "aarch64"
git-tree-sha1 = "f02beedf60c0c070d56f00d08b5c828b8d6b1d52"
os = "macos"

    [[pocl_standalone.download]]
    sha256 = "0fb6832afd321ee84894d88a39e4995d8ea64d881664c83be5c2e2f705d717af"
    url = "https://github.com/JuliaBinaryWrappers/pocl_standalone_jll.jl/releases/download/pocl_standalone-v7.1.2+2/pocl_standalone.v7.1.2.aarch64-apple-darwin.tar.gz"
[[pocl_standalone]]
arch = "x86_64"
git-tree-sha1 = "c6c1e633fbbde99ed0dddde20be4132b67b6b0a6"
os = "freebsd"

    [[pocl_standalone.download]]
    sha256 = "02c9bdbc3e9d3fc00bcb466c8087e46789c1d99dae303a733b05691f205f4012"
    url = "https://github.com/JuliaBinaryWrappers/pocl_standalone_jll.jl/releases/download/pocl_standalone-v7.1.2+2/pocl_standalone.v7.1.2.x86_64-unknown-freebsd.tar.gz"
[[pocl_standalone]]
arch = "aarch64"
git-tree-sha1 = "c83a776132765a67934e356e7065146a3da42fbd"
os = "freebsd"

    [[pocl_standalone.download]]
    sha256 = "b7186c72adf91d3609e27ea01924662917db10e222431d9e52b981f9f747b16c"
    url = "https://github.com/JuliaBinaryWrappers/pocl_standalone_jll.jl/releases/download/pocl_standalone-v7.1.2+2/pocl_standalone.v7.1.2.aarch64-unknown-freebsd.tar.gz"
[[pocl_standalone]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0dbf484050a0e2ffd9f4dd27182e9a5c2290afbe"
os = "windows"

    [[pocl_standalone.download]]
    sha256 = "2bdabea2fac4c4328353ed48771272b02125fc99159bac205ec21677bac6726e"
    url = "https://github.com/JuliaBinaryWrappers/pocl_standalone_jll.jl/releases/download/pocl_standalone-v7.1.2+2/pocl_standalone.v7.1.2.x86_64-w64-mingw32-cxx11.tar.gz"
