# Autogenerated wrapper script for pocl_standalone_jll for x86_64-unknown-freebsd
export libpocl, poclcc

using Hwloc_jll
using Zstd_jll
using SLEEF_jll
JLLWrappers.@generate_wrapper_header("pocl_standalone")
JLLWrappers.@declare_library_product(libpocl, "libpocl_standalone.so.2")
JLLWrappers.@declare_executable_product(poclcc)
function __init__()
    JLLWrappers.@generate_init_header(Hwloc_jll, Zstd_jll, SLEEF_jll)
    JLLWrappers.@init_library_product(
        libpocl,
        "lib/libpocl_standalone.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        poclcc,
        "bin/poclcc",
    )

    JLLWrappers.@generate_init_footer()
    # Nothing to initialize: the standalone JIT build is fully self-contained
# (no ICD driver to register, no external tools to locate).

end  # __init__()
