# Autogenerated wrapper script for pocl_standalone_jll for x86_64-w64-mingw32-cxx11
export libpocl, poclcc

using Hwloc_jll
using Zstd_jll
JLLWrappers.@generate_wrapper_header("pocl_standalone")
JLLWrappers.@declare_library_product(libpocl, "pocl_standalone.dll")
JLLWrappers.@declare_executable_product(poclcc)
function __init__()
    JLLWrappers.@generate_init_header(Hwloc_jll, Zstd_jll)
    JLLWrappers.@init_library_product(
        libpocl,
        "bin\\pocl_standalone.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        poclcc,
        "bin\\poclcc.exe",
    )

    JLLWrappers.@generate_init_footer()
    # Nothing to initialize: the standalone JIT build is fully self-contained
# (no ICD driver to register, no external tools to locate).

end  # __init__()
